# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vijc2e9TRdc4BBb_gzJDxp2piHO4uawT

# Load model, parameters, performance metrics
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import torch
from modules import VQVAE
import matplotlib.pyplot as plt
import numpy as np
from ssimindex import calculate_ssim

# %matplotlib inline
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

"""
Utility functions
"""

def load_model(model_filename):
    path = os.getcwd()

    if torch.cuda.is_available():
        data = torch.load(path + model_filename,weights_only=False)
    else:
        data = torch.load(path+model_filename,map_location=lambda storage, loc: storage,weights_only=False)

    params = data["hyperparameters"]

    model = VQVAE(params['n_hiddens'], params['n_residual_hiddens'],
                  params['n_residual_layers'], params['n_embeddings'],
                  params['embedding_dim'], params['beta']).to(device)

    model.load_state_dict(data['model'])

    return model, data

from scipy.signal import savgol_filter

def plot_metrics(data):
    results = data["results"]
    recon_errors = savgol_filter(results["recon_errors"], 19, 5)
    perplexities = savgol_filter(results["perplexities"], 19, 5)
    loss_vals = savgol_filter(results["loss_vals"], 19, 5)
    val_recon_errors = savgol_filter(results["val_recon_errors"], 19, 5)
    val_loss = savgol_filter(results["val_loss_vals"], 19, 5)
    ssim = savgol_filter(results["ssim"], 19, 5)


    f = plt.figure(figsize=(16,4))
    ax = f.add_subplot(1,4,2)
    ax.plot(recon_errors, label='training')
    ax.plot(val_recon_errors, label='validation')
    ax.set_yscale('log')
    ax.set_title('Reconstruction Error')
    ax.set_xlabel('iteration')

    ax = f.add_subplot(1,4,4)
    ax.plot(perplexities)
    ax.set_title('Average codebook usage (perplexity).')
    ax.set_xlabel('iteration')

    ax = f.add_subplot(1,4,1)
    ax.plot(loss_vals, label='training')
    ax.plot(val_loss, label='validation')
    ax.set_yscale('log')
    ax.set_title('Overall Loss')
    ax.set_xlabel('iteration')

    ax = f.add_subplot(1,4,3)
    ax.plot(ssim)
    ax.set_title('SSIM')
    ax.set_xlabel('iteration')


    ax.legend()

    plt.savefig("metrics.png")
    plt.close()

def display_image_grid(x, name, labels=None):
    x = x.cpu().detach()+0.5
    x = x.numpy()
    fig = plt.figure(figsize=(8, 8))
    cols = 8
    rows = 4
    for i in range(1, cols*rows + 1):
        label = ""
        if labels is not None:
            label = labels[i - 1]
        ax = fig.add_subplot(rows, cols, i)
        ax.set_title(label)
        plt.imshow(np.transpose(x[i - 1], (1,2,0)), interpolation='nearest')
        plt.axis('off')
    plt.savefig(f'{name}.png')

def reconstruct(data_loader,model):
    (x, _) = next(iter(data_loader))
    x = x.to(device)
    model.eval()
    with torch.no_grad():
        _, x_recon, _ = model(x)
    return x,x_recon

"""
End of utilities
"""

model_filename = '/vqvae_data_sun_oct_19_22_46_34_2025.pth'

model,vqvae_data = load_model(model_filename)


"""# Load dataset and loaders"""

import utils
training_data, test_data, training_loader, test_loader, x_train_var, x_test_var = utils.load_data_and_data_loaders(32, True)

"""# Reconstruct validation data"""

x_test,x_test_recon = reconstruct(test_loader,model)
display_image_grid(x_test, 'validation_data')

labels = []
for i in range(32):
    x_t = torch.unsqueeze(x_test[i], dim=0)
    x_r = torch.unsqueeze(x_test_recon[i], dim=0)
    labels.append(round(calculate_ssim(x_t, x_r), 3))

display_image_grid(x_test_recon, 'validation_data_reconstruction', labels)

"""# Smoothed Loss and Perplexity Values"""

plot_metrics(vqvae_data)